-- MySQL Script generated by MySQL Workbench
-- Wed Oct 19 10:57:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PROVEIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVEIDOR` (
  `Id_Proveidor` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Adreça` VARCHAR(128) NULL,
  `Codi Postal` VARCHAR(12) NULL,
  `Ciutat` VARCHAR(60) NULL,
  `Telefon` VARCHAR(20) NULL,
  `Fax` VARCHAR(20) NULL,
  `NIF` VARCHAR(20) NULL,
  PRIMARY KEY (`Id_Proveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUNTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUNTURA` (
  `ID_Muntura` INT NOT NULL,
  `TipusMuntura` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_Muntura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ULLERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ULLERES` (
  `ID_Ulleres` INT NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `GraduacioVidreDret` FLOAT NULL,
  `GraduacioVidreEsquerra` FLOAT NULL,
  `Montura` INT NULL,
  `ColorMontura` VARCHAR(45) NULL,
  `ColorVidreDret` VARCHAR(45) NULL,
  `ColorVidreEsquerra` VARCHAR(45) NULL,
  `MUNTURA_id` INT NOT NULL,
  PRIMARY KEY (`ID_Ulleres`),
  INDEX `fk_ULLERES_MUNTURA_idx` (`MUNTURA_id` ASC, `Montura` ASC) VISIBLE,
  CONSTRAINT `fk_ULLERES_MUNTURA`
    FOREIGN KEY (`MUNTURA_id` , `Montura`)
    REFERENCES `mydb`.`MUNTURA` (`ID_Muntura` , `ID_Muntura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REFERITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REFERITS` (
  `ID_Referit` INT NOT NULL,
  `ID_ClientNou` INT NULL,
  `ID_ClientReferit` INT NULL,
  PRIMARY KEY (`ID_Referit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDES` (
  `ID_Venda` INT NOT NULL,
  `ID_Ulleres` INT NULL,
  `ID_Client` INT NULL,
  `ID_Empleat` INT NULL,
  `DataVenta` DATE NULL,
  `ULLERES_id` INT NOT NULL,
  PRIMARY KEY (`ID_Venda`),
  INDEX `fk_VENDES_ULLERES1_idx` (`ULLERES_id` ASC) VISIBLE,
  CONSTRAINT `fk_VENDES_ULLERES1`
    FOREIGN KEY (`ULLERES_id`)
    REFERENCES `mydb`.`ULLERES` (`ID_Ulleres`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTS` (
  `ID_Client` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Adreça` VARCHAR(128) NULL,
  `CodiPostal` VARCHAR(12) NULL,
  `Ciutat` VARCHAR(60) NULL,
  `Telefon` VARCHAR(20) NULL,
  `Email` VARCHAR(100) NULL,
  `DataRegistre` DATE NULL,
  `REFERITS_id` INT NOT NULL,
  `VENDES_id` INT NOT NULL,
  PRIMARY KEY (`ID_Client`),
  INDEX `fk_CLIENTS_REFERITS1_idx` (`ID_Client` ASC, `REFERITS_id` ASC) VISIBLE,
  INDEX `fk_CLIENTS_VENDES1_idx` (`VENDES_id` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTS_REFERITS1`
    FOREIGN KEY (`ID_Client` , `REFERITS_id`)
    REFERENCES `mydb`.`REFERITS` (`ID_Referit` , `ID_Referit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENTS_VENDES1`
    FOREIGN KEY (`VENDES_id`)
    REFERENCES `mydb`.`VENDES` (`ID_Venda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEAT` (
  `ID_Empleat` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `VENDES_id` INT NOT NULL,
  PRIMARY KEY (`ID_Empleat`),
  INDEX `fk_EMPLEAT_VENDES1_idx` (`VENDES_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEAT_VENDES1`
    FOREIGN KEY (`VENDES_id`)
    REFERENCES `mydb`.`VENDES` (`ID_Venda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
